### ISSUE TITLE
Is "Enhanced Mutamin's Garden" a prereq to "Enhanced Ramazith's Tower"?

### ISSUE THREAD

**Issue by ChitownWillie** [AngelGryph/MadeInHeaven_EncountersAndQuests#1]
Skipping "Enhanced Mutamin's Garden" and installing "Enhanced Ramazith's Tower" results in:

_FAILURE:
Adding non-existent actor basill to area!
ERROR: [AR7242.are] -> [override] Patching Failed (COPY) (Failure("Adding non-ex
istent actor basill to area!"))
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Enhanced Ramazith's Tower], rolling back to previous state
Will uninstall   4 files for [MIH_EQ/SETUP-MIH_EQ.TP2] component 2.
Uninstalled      4 files for [MIH_EQ/SETUP-MIH_EQ.TP2] component 2.
ERROR: Failure("Adding non-existent actor basill to area!")
Please make a backup of the file: SETUP-MIH_EQ.DEBUG and look for support at: angel@pearlgates.net_

**Comment by AngelGryph** [comment]
BGT-specific bug, has been fixed in newer releases.
