### ISSUE TITLE
Request: Include subtledoctor's Black Pits bug fix.

### ISSUE THREAD

**Issue by Endarire** [AngelGryph/MadeInHeaven_EncountersAndQuests#10]
Greetings, @AngelGryph!

[Here, subtledoctor released a hotfix to allow Black Pits to work with your MiH EQ and other mods](https://github.com/subtledoctor/SubtleD_hotfixes/releases/tag/v29).  I request you integrate it into your codebase of MiH EQ on GitHub.

Thankee!

**Comment by AngelGryph** [comment]
Already fixed by other means.
