### ISSUE TITLE
Immortal Dread Wolf

### ISSUE THREAD

**Issue by morpheus562** [AngelGryph/MadeInHeaven_EncountersAndQuests#12]
I have been finding Dread Wolves, especially those present in ToB, to be completely immortal. I am guessing there is a script bug where the min1hp is not being removed.

I had a pack of them chasing me throughout Sendai's enclave as they were going from area to area with me and not dying.

**Comment by AngelGryph** [comment]
I have nothing to do with any dread wolves anywhere in ToB.

**Comment by morpheus562** [comment]
But it still uses the dreadwolf creature changes implemented by MiH.

**Comment by AngelGryph** [comment]
If another mod screws up my scripting, there is literally nothing I can do about it.

**Comment by AngelGryph** [comment]
Cannot fix.
