### ISSUE TITLE
small bugs

### ISSUE THREAD

**Issue by TotoR115** [AngelGryph/MadeInHeaven_EncountersAndQuests#2]
The following components use BGEE animate.ids references and prevent installation of some components on classic BG2 (with IAb5) :

- illithid_activities.tpa -- umber_hulk_elder for EE, is UMBERHULK_IWD for BG2
- install_giants.tpa -- giant_frost in EE is frost_giant in BG2
                              -- giant_hill in EE is VERBEEG in BG2
- white_dracolich.tpa -- dragon_white in EE is DRAGON_WHITE_YOUNG in BG2

For the following script directions are in letters (EE) instead of figures (classic BG2 and EE) :
- spawn_nature_elementals.baf -- CreateCreature("cutspy", [710.750], S) the S should be a 0

In mhtomb.are, the rest encounters, RNDPSPD.cre, does not exist in classic BG2 ; I don't know for EE. in classic BG2, there is another random spider: RDSPIDER.cre

**Comment by AngelGryph** [comment]
I'm aware of the animation issues and am working on them, but dealing with all the different versions is a serious pain.  The current version should be a little smarter with it but it may not use IA animations correctly.

**Comment by TotoR115** [comment]
This version is clearly smarter to do it... however, there is still an issue with the animation that prevent from installing this mod : in `animations.2da` the Fallback `revenant` does not exist in anim.ids.

- For oBG2 it is `reveant` without the "n" and for IAb5 it is `GHOUL_REVENANT`

Don't know if it is game breaking but the following bug are still present :

- spawn_nature_elementals.baf -- CreateCreature("cutspy", [710.750], **S**) ; directions in lettre don't work for oBG2
- In mhtomb.are, the rest encounters, **RNDPSPD.cre**, does not exist in oBG2 ;

In addition, I don't know if it is armfull but, for oBG2 you use stats that are not initialize in detectable spells library leading to parse error during installation (for the reccord it is the same in NToTSC mod, last version from gitHub version https://github.com/SpellholdStudios/NTotSC/issues/27) -- I think that you only need to create a ds table the with [PRIORITY_DISPEL] for this mod and with [STATE_DISABLED] for NToTSC

**Comment by AngelGryph** [comment]
> For oBG2 it is `reveant` without the "n" and for IAb5 it is `GHOUL_REVENANT`

The misspelling is covered in lib/lib_ids.tpa, it will add the correctly spelled entry if it is missing.
`APPEND "animate.ids"    "0x7701 REVENANT"               UNLESS "REVENANT"`

> spawn_nature_elementals.baf -- CreateCreature("cutspy", [710.750], **S**) ;
> directions in letter don't work for oBG2

Actually it does support this, if you provide the missing dir.ids and make a small edit to action.ids.  This is covered in lib/missing_files.tpa.
```
ACTION_IF NOT FILE_EXISTS_IN_GAME "dir.ids"
BEGIN
  LAUNCH_ACTION_FUNCTION install
    STR_VAR
    file        = "dir.ids"
    location    = "resource/missing"
  END

  LAUNCH_ACTION_FUNCTION swap_text
    STR_VAR
    file        = "action.ids"
    swaps       = ~"I:Face\*" => "I:Face*DIR"~
  END
END
```

> In mhtomb.are, the rest encounters, **RNDPSPD.cre**, does not exist in oBG2 ;

Good catch!  I doubt anyone would have fun into it with an inn two screens away, but I guess I should fix it anyway.

> In addition, I don't know if it is harmful but, for oBG2 you use stats that are not initialize in detectable spells library leading to
> parse error during installation (for the record it is the same in NToTSC mod, last version from gitHub version
> [SpellholdStudios/NTotSC#27](https://github.com/SpellholdStudios/NTotSC/issues/27)) -- I think that you only need to create a
> ds table the with [PRIORITY_DISPEL] for this mod and with [STATE_DISABLED] for NToTSC

Mm... Unfortunately the inner workings of advanced AI scripting and detectable spells are still a little beyond me, this code was lifted practically verbatim from SCS.  The NTotSC issue is likely just a missing state.ids entry similar to CD_STATE_INVALID but for this one I am not so sure.  I will work on it, but this may take me some time.  I *think* it's mostly harmless though, just causes huecuva to use Dispel Magic less effectively.

**Comment by TotoR115** [comment]
> The misspelling is covered in lib/lib_ids.tpa, it will add the correctly spelled entry if it is missing.

Strange because I have an installation error with this mod on oBG2 during megamod installation... I will have to investigate this because the error is clearly link to the `revenant` entry... 

 **Edited** : The incompatibility come from RBG1MPV mod (RESTORED BG1 MONSTER PALETTE VARIANTS).... this mod created an entry named : `REVENANT_FIXED`. the `animations.2da` check doesn't make the difference between `REVENANT` and `REVENANT_FIXED`... it's an edge case that could be addressed. it's up to you.

> Actually it does support this, if you provide the missing dir.ids and make a small edit to action.ids. This is covered in lib/missing_files.tpa.

Thats great I was not sure that the `dir.ids` was working on oBG2.

> I will work on it, but this may take me some time. I think it's mostly harmless though, just causes huecuva to use Dispel Magic less effectively.

Maybe this can help you : if you look in stratagems folder for ds, you will find `ds_scs.tpa`. I think that in this file, there is a table that create the needed dependency :

> <<<<<<<< .../ds-inline/PRIORITY_DISPEL.2da
resource
WIZARD_PROTECTION_FROM_MAGIC_WEAPONS
WIZARD_MANTLE
WIZARD_IMPROVED_MANTLE
WIZARD_ABSOLUTE_IMMUNITY
POTN35  // magic shielding
WIZARD_PROTECTION_FROM_MAGIC_ENERGY
CLERIC_CHAOTIC_COMMANDS
POTN04 // these are all Giant Strength
POTN05
POTN06
POTN07
POTN12
WIZARD_HASTE
WIZARD_ADVANCED_HASTE
CLERIC_SHIELD_OF_LATHANDER
CLERIC_GREATER_SHIELD_OF_LATHANDER
CLERIC_IMPERVIOUS_SANCTITY_OF_MIND
WIZARD_MIND_BLANK
**>>>>>>>>**

**Comment by AngelGryph** [comment]
> Strange because I have an installation error with this mod on oBG2 during megamod installation... I will have to investigate
> this because the error is clearly link to the `revenant` entry...
> 
> **Edited** : The incompatibility come from RBG1MPV mod (RESTORED BG1 MONSTER PALETTE VARIANTS).... this mod
> created an entry named : `REVENANT_FIXED`. the `animations.2da` check doesn't make the difference between
> `REVENANT` and `REVENANT_FIXED`... it's an edge case that could be addressed. it's up to you.

Ah yes, that would explain it.  Well, lib_ids.tpa is a legacy piece of code I swiped from somewhere, might as well modernize it a bit.

> Maybe this can help you : if you look in stratagems folder for ds, you will find `ds_scs.tpa`. I think that in this file, there is
> a table that create the needed dependency :

Mm, I'll do what I can, but this whole AI and DS stuff still has a lot of mysteries to me, and DavidW's code isn't exactly the simplest to comprehend. ^^

**Comment by AngelGryph** [comment]
Alright, I found a solution to the PRIORITY_DISPEL issue.  First of all, this requires EE or ToBEx.   Without either, Detectable Spells simply won't work at all and won't even try to make spells detectable.  Note that unlike SCS I do not currently include ToBEx, if you use the old engine you have to install it on your own (preferably before G3 Fixpack which is btw also requirted).

As you correctly found out, PRIORITY_DISPEL is not standard in DS; SCS adds it later.  I have added this functionality as well, in a way that (hopefully) does not conflict with SCS regardless of install order.

I will be whipping up a new release shortly, I'm currently thinking on if I can improve the handling of animations better.
